services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: test_sample
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data: